# .github/labeler.yml
# https://github.com/marketplace/actions/multi-labeler
# @todo: sync with other repo
version: v1

labels:
  - label: "kind/feature"
    sync: true # remove label if match failed, default: false (pull_request/issue only)
    matcher:
      title: "^feat:.*"
      body: "/feat"
      comment: "/feat"
      branch: "^feat/.*"
      commits: "^feat:.*"
      author:
        - github-actions
      files:
        any: [ "src/*" ]
        all: [ "!app/config/**" ]
        count:
          gte: 1
          lte: 1000

  - label: "kind/bug"
    sync: true # remove label if match failed, default: false (pull_request/issue only)
    matcher:
      # Matcher will match on any 7 matcher
      title: "^fix:.*"
      # e.g. '- [x] bug'
      body: "(\\n|.)*- \\[x\\] bug(\\n|.)*"
      comment: "/fix"
      branch: "^fix/.*"
      commits: "^fix:.*"

  - label: "kind/chore"
    sync: true # remove label if match failed, default: false (pull_request/issue only)
    matcher:
      title: "^chore:.*"
      body: "(\\n|.)*- \\[x\\] chore(\\n|.)*"
      comment: "/chore"
      branch: "^chore/.*"
      commits: "^chore:.*"

  - label: "coverage"
    matcher:
      comment: "# \\[Codecov\\] .*"

  - label: ":skull: stale"
    matcher:
      comment: "/stale"

  - label: "kind/github"
    sync: true
    matcher:
      # This is shorthand for any: [".github/**"]
      files: ".github/**"

  - label: ':robot: bot'
    sync: true
    matcher:
      - github-actions
      - rennovate
      - dependabot
      - dependabot[bot]
      - dependabot-preview[bot]
      - renovate[bot]
      - renovate-bot

  - label: ":robot: ci"
    sync: true
    matcher:
      files:
        any: [ ".github/**", ]
        all: [ "!app/**" ]

  # PR Files Count
  - label: ":smiley_cat: size S"
    sync: true
    matcher:
      files:
        count:
          gte: 1
          lte: 4

  - label: ":nauseated_face: size M"
    sync: true
    matcher:
      files:
        count:
          gte: 5
          lte: 10

  - label: ":skull_and_crossbones: size L"
    sync: true
    matcher:
      files:
        count:
          gte: 11
          lte: 20

  - label: ":hourglass_flowing_sand: size XL"
    sync: true
    matcher:
      files:
        count:
          gte: 20

  - label: ":memo: documentation"
    sync: true # remove label if match failed, default: false (pull_request/issue only)
    matcher:
      # Matcher will match on any 7 matcher
      title: "^docs:.*"
      commits: "^docs:.*"
      files:
        any: [ "README.md'", "CHANGELOG.md" ]

  - label: 'kind/refactor'
    matcher:
      title: '^refactor(\(|:)'

  - label: 'kind/common'
    matcher:
      title: '\(.*common.*\):'

# Optional, if you want labels to generate a success/failure status check
checks:
  - context: "merge status check"
    url: "https://docs.github.com/en/rest/reference/checks"
    description:
      success: "Ready for merge."
      failure: "Missing labels for merge."
    labels:
      any:
        - ':robot: bot'
        - ':bell: automerge'
      all:
        - '✅ Approved'
